### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by Deph0** [ryanramage/deluge-add#1]
Hi, every time i try to use this, i get this error in return and the deluge daemon stops working, even for the webui.

```javascript
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
I've copypasted your example and just changed the magnet url, password and host.

**Comment by Deph0** [comment]
Nevermind, found a better npm package, [ginman86/deluge](https://github.com/ginman86/deluge)
